#!/bin/bash

set -o nounset
set -o errexit

. sqlevolveconf
tmploc='/tmp/sqlevolve.sql'

db () {
  psql --set ON_ERROR_STOP= --single-transaction -f "$1" "$dbname"
}

dbScalar () {
  local res=$(psql --set ON_ERROR_STOP= -t -c "$1" $dbname)
  echo ${res//[:space:]/}
}

evolve () {
  local file="$1"
  local direction="$2"
  local isReadingUp=true
  echo ''
  echo "$1..."

  # transfer the right section to the tmp file
  echo "" > "$tmploc"
  while read line; do
    [[ "$line" = '-- DOWN' ]] && isReadingUp=false
    # If we're going up, don't read the down
    [[ "$direction" = 'up' ]]  && ! $isReadingUp && break
    # If we're going down, don't read the up
    [[ "$direction" = 'down' ]] && $isReadingUp && continue
    echo "$line" >> "$tmploc"
  done < "$file"

  # execute the tmp file
  db "$tmploc"

  # update the version. A correction must be made to the target if we're
  # moving down because the resulting version of a "down" is 1 less than the
  # script we are running
  local current="$(dbScalar 'select * from version;')"
  local target="${file%.sql}"
  [[ "$direction" = 'down' ]] && target=$(( target - 1 ))
  dbScalar "update version set version=$target where version=$current;"
  echo "...done!"
}

max () {
  local max="$1"
  for v in "$@" ; do
    [[ "$v" -gt "$max" ]] && max="$v"
  done
  echo "$max"
}

quit () {
  echo "INFO: Evolution complete!"
  exit 0
}

echo "INFO: sqlevolve is running on database \"$dbname\" in dir \"$(pwd)\""

sqls=$(ls | grep 'sql$')

# Get target version
if [[ $# = 0 ]] ; then
  target=$(max $(echo "$sqls" | sed 's/.sql//'))
  echo "INFO: No target given, will use the highest evolution found."
else
  target="$1"
fi
echo "INFO: Targeting: ${target}.sql"

# Get current version
current=$(dbScalar 'select * from version;')
echo "INFO: Current version: $current"

# Get direction
if [[ $current = $target ]] ; then
  quit
elif [[ $current -lt $target ]] ; then
  direction="up"
else
  direction="down"
fi
echo "INFO: Evolving $direction"

# Get relevant scripts and run them
if [[ $direction = 'up' ]] ; then
  for file in $(echo "$sqls" | sort -n) ; do
    i="${file%.sql}"
    [[ "$i" -gt $current && "$i" -le $target ]] && evolve "$file" "$direction"
  done
else
  for file in $(echo "$sqls" | sort -nr) ; do
    i="${file%.sql}"
    [[ "$i" -le $current && "$i" -gt $target ]] && evolve "$file" "$direction"
  done
fi

quit

